sudo: false
language: c
compiler:
  - clang
  - gcc
os:
  - linux
env:
  matrix:
    - BUILD_TYPE=Debug     STACK_ONLY=ON    THREAD_SUPPORT=ON
    - BUILD_TYPE=Debug     STACK_ONLY=ON    THREAD_SUPPORT=OFF
    - BUILD_TYPE=Release   STACK_ONLY=ON    THREAD_SUPPORT=ON
    - BUILD_TYPE=Release   STACK_ONLY=ON    THREAD_SUPPORT=OFF
    - BUILD_TYPE=Debug     STACK_ONLY=OFF   THREAD_SUPPORT=ON
    - BUILD_TYPE=Debug     STACK_ONLY=OFF   THREAD_SUPPORT=OFF
    - BUILD_TYPE=Release   STACK_ONLY=OFF   THREAD_SUPPORT=ON
    - BUILD_TYPE=Release   STACK_ONLY=OFF   THREAD_SUPPORT=OFF

addons:
  apt:
    packages:
      - cmake
      - libarchive-dev
      - libjansson-dev
      - libjson-c-dev
      - libcurl4-openssl-dev

install:
  - mkdir build
  - cd build
  - ../build.sh

before_script:
  - cmake --version

script:
  - make
  - make check
  - make package

