# System vendor
IOT_VENDOR: Wind River Systems
IOT_PRODUCT: Helix Device Cloud
IOT_PRODUCT_SHORT: hdc
IOT_LIBRARY_NAME: iot

# Library version
IOT_VERSION: 2.Next
IOT_VERSION_MAJOR: 2
IOT_VERSION_MINOR: 4
IOT_VERSION_PATCH: 0
IOT_VERSION_TWEAK: 0

# Limits
IOT_ACTION_MAX: 255
IOT_ACTION_STACK_MAX: 3
IOT_ACTION_QUEUE_MAX: 10
IOT_OPTION_MAX: 20
IOT_PARAMETER_MAX: 7
IOT_SAMPLE_MAX: 10
IOT_TELEMETRY_STACK_MAX: 3
IOT_TELEMETRY_MAX: 255
IOT_WORKER_THREADS: 5

# Helper applications
IOT_UPDATE_TARGET: "iot-update"
IOT_CONTROL_TARGET: "iot-control"

# Defauilt directories
IOT_CONFIG_DIR_DEFAULT: "/etc/iot"
IOT_RUNTIME_DIR_DEFAULT: "/var/lib/iot"

# Plugin options
IOT_PLUGIN_MAX: 5
IOT_PLUGIN_BUILTIN:
  - tr50: on

# config files
IOT_CFG: "iot.cfg"
IOT_USER: "iot"

# default actions for device manager
IOT_DEFAULT_ENABLE_AGENT_RESET_C: 1
IOT_DEFAULT_ENABLE_DECOMMISSION_DEVICE_C: 1
IOT_DEFAULT_ENABLE_DEVICE_REBOOT_C: 1
IOT_DEFAULT_ENABLE_DEVICE_SHUTDOWN_C: 1
IOT_DEFAULT_ENABLE_DUMP_LOG_FILES_C: 1
IOT_DEFAULT_ENABLE_FILE_TRANSFERS_C: 1
IOT_DEFAULT_ENABLE_REMOTE_LOGIN_C: 1
IOT_DEFAULT_ENABLE_RESTORE_FACTORY_IMAGES_C: 0
IOT_DEFAULT_ENABLE_SOFTWARE_UPDATE_C: 1

# default settings for device manager
IOT_DEFAULT_ENABLE_PERSISTENT_ACTIONS_C: 0
IOT_DEFAULT_ENABLE_AUTOMATION_TEST_ON_ANDROID_C: 1
IOT_DEFAULT_UPLOAD_REMOVE_ON_SUCCESS_C: 0
IOT_DEFAULT_SSL_VALIDATION_C: 1

# default ssl CA bundle
IOT_DEFAULT_CERT_PATH: "/etc/ssl/certs/ca-certificates.crt"
