# System vendor
IOT_VENDOR: Wind River Systems
IOT_PRODUCT: Helix Device Cloud
IOT_PRODUCT_SHORT: hdc
IOT_LIBRARY_NAME: iot

# Library version
IOT_VERSION: 2.Next
IOT_VERSION_MAJOR: 2
IOT_VERSION_MINOR: 4
IOT_VERSION_PATCH: 0
IOT_VERSION_TWEAK: 0

# Limits
IOT_ACTION_MAX: 255
IOT_ACTION_STACK_MAX: 3
IOT_ACTION_QUEUE_MAX: 10
IOT_OPTION_MAX: 20
IOT_PARAMETER_MAX: 7
IOT_SAMPLE_MAX: 10
IOT_TELEMETRY_STACK_MAX: 3
IOT_TELEMETRY_MAX: 255
IOT_WORKER_THREADS: 5

# Helper applications
IOT_UPDATE_TARGET: "iot-update"
IOT_CONTROL_TARGET: "iot-control"

# Defauilt directories
IOT_CONFIG_DIR_DEFAULT: "/etc/iot"
IOT_RUNTIME_DIR_DEFAULT: "/var/lib/iot"

# Plugin options
IOT_PLUGIN_MAX: 5
IOT_PLUGIN_BUILTIN:
  - tr50: on
